# Generated by Django 4.1.2 on 2022-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_user_listing_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
